stages:
  extract_data:
    cmd: python pipeline/extract.py
    deps:
      - pipeline/extract.py
    outs:
      - output_dir/dataset
    params:
      - extract_data

  train_model:
    cmd: python pipeline/train.py
    deps:
      - pipeline/train.py
      - train_distributed.py
      - lib/training.py
      - output_dir/dataset
    outs:
      - output_dir/gpt2-1b-russian
      - output_dir/tensorboard/train_model
    metrics:
      - output_dir/metrics/train_model.json
    plots:
      - output_dir/plots/train_model_history.csv:
          x: step
          y: loss
    params:
      - train_model

  export_onnx:
    cmd: python pipeline/export.py
    deps:
      - pipeline/export.py
      - export_onnx.py
      - output_dir/gpt2-1b-russian
    outs:
      - output_dir/onnx
    params:
      - export_onnx

